# Generated by Django 2.2.2 on 2019-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='division_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='league_value',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='region_value',
            field=models.CharField(default='-', max_length=3),
            preserve_default=False,
        ),
    ]
