# Generated by Django 2.2.3 on 2019-07-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190613_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='division_value',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='league_value',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='main_champion',
        ),
        migrations.AddField(
            model_name='summoner',
            name='uid',
            field=models.CharField(default='1yxmxO2pqEykY1rl', max_length=16, primary_key=True, serialize=False),
        ),
    ]
