# Generated by Django 2.2.3 on 2019-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190703_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='uid',
            field=models.CharField(default='f5202b', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
