# Generated by Django 2.2.3 on 2019-07-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190703_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='uid',
            field=models.CharField(default='93ff170efe6240c3a9fe', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
