# Generated by Django 2.2.3 on 2019-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190703_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='uid',
            field=models.CharField(default='hIFcvWg0', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
