# Generated by Django 2.2.3 on 2019-07-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190703_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='uid',
        ),
        migrations.AddField(
            model_name='summoner',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='url',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='region_value',
            field=models.CharField(choices=[('la1', 'LAS'), ('la2', 'LAN'), ('na', 'NA'), ('br1', 'BR')], max_length=3),
        ),
    ]
