# Generated by Django 2.2.3 on 2019-07-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190703_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
