# Generated by Django 2.2.3 on 2019-07-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190703_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='region_value',
            field=models.CharField(choices=[('la1', 'LAN'), ('la2', 'LAS'), ('na', 'NA'), ('br1', 'BR')], max_length=3),
        ),
    ]
